name: Release
on:
  workflow_dispatch:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
      with:
        bundler-cache: true
    - name: Install dependencies
      run: if [[ $(uname) == "Darwin" ]]; then brew install graphviz; else sudo apt-get install graphviz; fi
    - name: Test
      run: bundle exec rake
    - name: Build
      run: gem build seafoam.gemspec
    - name: Upload
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: release-build
        path: 'seafoam-*.gem'
