name: Release
on:
  workflow_dispatch:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: ruby/setup-ruby@4c24fa5ec04b2e79eb40571b1cee2a0d2b705771 # v1.278.0
      with:
        bundler-cache: true
    - name: Install dependencies
      run: if [[ $(uname) == "Darwin" ]]; then brew install graphviz; else sudo apt-get install graphviz; fi
    - name: Test
      run: bundle exec rake
    - name: Build
      run: gem build seafoam.gemspec
    - name: Upload
      uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
      with:
        name: release-build
        path: 'seafoam-*.gem'
